"""
Synork Home — Pairing Handshake Schema

Types for the device-to-Synork pairing flow. Supports three network paths:
  1. Ethernet + mDNS (v1 primary)
  2. WiFi AP captive portal (v1 fallback)
  3. BLE provisioning (v1.5)

The pairing flow:
  1. Device boots → generates PairingToken → advertises via mDNS/AP/BLE
  2. Synork app discovers device → sends PairingRequest
  3. Device responds with PairingChallenge (6-digit code on screen/LED)
  4. User enters code in app → app sends PairingConfirmation
  5. If code matches → relay issues PairingComplete → device linked to household

Security:
  - 5-minute pairing window after first boot, then locked
  - 6-digit code validated against token (not just any 6 digits)
  - BLE proximity validation when available
  - First valid pairing locks the device; re-pairing requires factory reset

Contract locked in Session 1 (2026-04-25).
Implementation: Session 2 (relay side) + Session 3 (addon side).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class PairingMethod(str, Enum):
    """How the device was discovered for pairing."""
    MDNS = "mdns"
    WIFI_AP = "wifi_ap"
    BLE = "ble"
    MANUAL = "manual"
    # Self-service install on an existing HA instance: the wizard is the
    # user-side UI and runs on the device itself (via HA ingress), so the
    # PIN-display dance is replaced by HA-admin auth + Synork user auth.
    # The backend's self_install endpoint short-circuits the PIN check.
    HA_ADDON_SELF_INSTALL = "ha_addon_self_install"


class PairingState(str, Enum):
    """State machine for the pairing flow."""
    AWAITING_DISCOVERY = "awaiting_discovery"
    DISCOVERED = "discovered"
    CHALLENGE_SENT = "challenge_sent"
    CODE_SUBMITTED = "code_submitted"
    VERIFIED = "verified"
    COMPLETE = "complete"
    FAILED = "failed"
    EXPIRED = "expired"
    LOCKED = "locked"


# ---------------------------------------------------------------------------
# Pairing types
# ---------------------------------------------------------------------------

class PairingToken(BaseModel):
    """
    Generated by the device on first boot.

    Stored locally on the device and used to validate incoming pairing
    requests. Expires after 5 minutes or first successful pairing.
    """
    token_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex,
        description="Unique identifier for this pairing token.",
    )
    device_id: str = Field(..., description="Unique device identifier (generated on first boot).")
    secret_hash: str = Field(
        ...,
        description="SHA-256 hash of the device secret (used for auth after pairing).",
    )
    pin_code: str = Field(
        ...,
        description="6-digit pairing code displayed to the user.",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When the token was generated.",
    )
    expires_at: datetime = Field(
        ...,
        description="Token expiration (5 minutes after creation).",
    )
    is_consumed: bool = Field(
        default=False,
        description="True after a successful pairing. Token cannot be reused.",
    )


class PairingRequest(BaseModel):
    """
    Sent from the Synork app to the device (or relay) to initiate pairing.

    Contains the user's Synork account info and the device identifier
    discovered via mDNS / AP / BLE.
    """
    request_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex,
        description="Unique pairing request identifier.",
    )
    user_id: str = Field(..., description="Synork account ID of the pairing user.")
    user_display_name: str = Field(..., description="Display name for the household setup.")
    device_id: str = Field(..., description="Device ID discovered during network scan.")
    method: PairingMethod = Field(..., description="How the device was discovered.")
    household_id: Optional[str] = Field(
        None,
        description="Existing household to add this device to. None = create new household.",
    )
    household_name: Optional[str] = Field(
        None,
        description="Name for new household (required if household_id is None).",
    )
    device_location: Optional[str] = Field(
        None,
        description="Room/area where the device is placed (user-provided during OOBE).",
    )
    app_version: str = Field(..., description="Version of the Synork app initiating pairing.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When the request was created.",
    )


class PairingChallenge(BaseModel):
    """
    Sent from the device back to the Synork app after receiving a PairingRequest.

    The 6-digit code is displayed on the device (screen, LED pattern, or
    spoken via TTS). The user must enter it in the Synork app to prove
    physical proximity.
    """
    request_id: str = Field(..., description="Matches the PairingRequest.request_id.")
    device_id: str = Field(..., description="Device identifier.")
    challenge_display: str = Field(
        ...,
        description=(
            "Human-readable hint for how the code is being displayed "
            "(e.g. 'on screen', 'LED blink pattern', 'spoken aloud')."
        ),
    )
    expires_at: datetime = Field(
        ...,
        description="Deadline for the user to enter the code.",
    )


class PairingConfirmation(BaseModel):
    """
    Sent from the Synork app after the user enters the 6-digit code.
    """
    request_id: str = Field(..., description="Matches the PairingRequest.request_id.")
    device_id: str = Field(..., description="Device identifier.")
    user_entered_code: str = Field(
        ...,
        min_length=6,
        max_length=6,
        description="The 6-digit code the user entered.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When the code was submitted.",
    )


class PairingComplete(BaseModel):
    """
    Sent from the relay to the device after successful pairing verification.

    Contains everything the device needs to start operating as part of
    the household.
    """
    request_id: str = Field(..., description="Matches the original PairingRequest.")
    device_id: str = Field(..., description="Device identifier.")
    household_id: str = Field(..., description="Household this device now belongs to.")
    household_name: str = Field(..., description="Human-readable household name.")
    device_secret: str = Field(
        ...,
        description=(
            "Shared secret for ongoing relay authentication (HMAC). "
            "Generated by the relay, stored securely on device."
        ),
    )
    relay_websocket_url: str = Field(
        ...,
        description="WebSocket URL the addon should connect to.",
    )
    relay_api_url: str = Field(
        ...,
        description="REST API URL for non-realtime operations.",
    )
    owner_user_id: str = Field(..., description="Synork user ID of the device owner.")
    paired_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When pairing was completed.",
    )


class NetworkConfig(BaseModel):
    """
    WiFi credentials passed during AP or BLE provisioning.

    Only used when the device doesn't have network access yet and the
    user needs to pass credentials during OOBE.
    """
    ssid: str = Field(..., description="WiFi network name.")
    passphrase: str = Field(
        ...,
        description="WiFi passphrase. Transmitted over encrypted BLE or local AP HTTPS.",
    )
    security_type: str = Field(
        default="wpa2",
        description="WiFi security type (wpa2, wpa3, open).",
    )
    hidden: bool = Field(
        default=False,
        description="Whether the network is hidden (not broadcasting SSID).",
    )
    ip_config: Optional[StaticIpConfig] = Field(
        None,
        description="Static IP configuration. None = use DHCP.",
    )


class StaticIpConfig(BaseModel):
    """Optional static IP configuration for devices that need it."""
    ip_address: str = Field(..., description="Static IP address.")
    subnet_mask: str = Field(default="255.255.255.0", description="Subnet mask.")
    gateway: str = Field(..., description="Default gateway.")
    dns_servers: list[str] = Field(
        default_factory=lambda: ["1.1.1.1", "8.8.8.8"],
        description="DNS server addresses.",
    )


# Fix forward reference — NetworkConfig references StaticIpConfig
NetworkConfig.model_rebuild()
